### ISSUE TITLE
More information on errors

### ISSUE THREAD

**Issue by beallch** [beeware/colosseum#41] opened 2019-06-09 23:00 UTC
After going through the how to contribute pages, and taking all the different steps I eventually get an error with the actual running of the test rather than a failed test. Is there any more documentation on where to look to fix these kinds of errors with tests?

This is my first time trying to contribute to open source, so if this is the wrong place to put this let me know, thanks for any help!

**Comment by freakboy3742** [comment] 2019-06-09 23:13
Welcome - and thanks for getting involved!

Unfortunately, no - there isn't any documentation about resolving errors in the test suite - but that's because there *shouldn't* be any errors in the test suite. We have CI system that runs the full test suite every time a patch is merged. So - if you're getting an error, it's definitely unexpected behavior. 

Can you provide any details about the error you're seeing, the environment where you're seeing that error, and the steps you've gone through to get to that point?

**Comment by freakboy3742** [comment] 2019-12-31 05:37
Closing due to lack of response.

**Closed by freakboy3742** 2019-12-31 05:37 UTC
